### ISSUE TITLE
Why Python and not Octave?

### ISSUE THREAD

**Issue by mankoff** [grinsted/pyimgraft#1]
I'm thrilled to see ImGRAFT not require MATLAB, but why all the effort to port to Python? It seems like porting to Octave would be an order of magnitude less effort.

**Comment by grinsted** [comment]
It probably would be. The primary motication for me was that teaching at NBI has switched to python.

 

Also, It was not that much effort really.

 

Aslak

 

From: Ken Mankoff ***@***.***> 
Sent: 8. april 2021 20:30
To: grinsted/pyimgraft ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [grinsted/pyimgraft] Why Python and not Octave? (#1)

 

I'm thrilled to see ImGRAFT not require MATLAB, but why all the effort to port to Python? It seems like porting to Octave would be an order of magnitude less effort.
